### ISSUE TITLE
Clear up Dependabot alerts

### ISSUE THREAD

**Issue by mike-parkhill** [docknetwork/developer-program#7]
See the Security tab for a list of reported vulnerabilities.

**Comment by mike-parkhill** [comment]
@robinbortlik, is this something you can look at when you're next working with this?

**Comment by robinbortlik** [comment]
@mike-parkhill will take a look on it tomorrow :)

**Comment by robinbortlik** [comment]
Hi @mike-parkhill , 

I'm very sorry, but I can't find any vulnerability reported. Is this the "security" tab you mentioned? https://github.com/docknetwork/developer-program/security

It seems there is not even dependabot configured. Do you want me to configure it?

Btw, this is just a static site generator, not code runs on server except build task running on github-actions . Do you think it is worthy to deal with dependabot it this case?

**Comment by mike-parkhill** [comment]
Dependabot is on and alerting me. Maybe you don't have access to see it: https://github.com/docknetwork/developer-program/security/dependabot
 
I'll check the permissions on that.

**Comment by mike-parkhill** [comment]
Check that link now - I think you should have access.

**Comment by robinbortlik** [comment]
@mike-parkhill works now :) Thanks
